### ISSUE TITLE
config/initializers/i18n_active_record.rb not working

### ISSUE THREAD

**Issue by D4v1dW3bb** [svenfuchs/i18n-active_record#104]
config/initializers/i18n_active_record.rb is configured like in the readme (auto generated)

translations from database are not loaded.

When placing:

require 'i18n/backend/active_record'
and
config.i18n.backend = I18n::Backend::Chain.new(I18n::Backend::ActiveRecord.new, I18n::Backend::Simple.new)

in config/application.rb translations from the db are loaded.

**Comment by dgeheniau** [comment]
Ok found the problem

You want to lookup first in db and then in files.
In the part of the code:

`if Translation.table_exists?
  I18n.backend = I18n::Backend::ActiveRecord.new

  I18n::Backend::ActiveRecord.send(:include, I18n::Backend::Memoize)
  I18n::Backend::Simple.send(:include, I18n::Backend::Memoize)
  I18n::Backend::Simple.send(:include, I18n::Backend::Pluralization)

  I18n.backend = I18n::Backend::Chain.new(I18n::Backend::Simple.new, I18n.backend)
end`

the part:

` I18n.backend = I18n::Backend::Chain.new(I18n::Backend::Simple.new, I18n.backend)`

should be replaced by:

` I18n.backend = I18n::Backend::Chain.new(I18n.backend, I18n::Backend::Simple.new)`

the first is the default and in the the autogenerated file teh Simple is the default and not the ActiveRecord!!!!

**Comment by timsly** [comment]
Sure, the AR backend can go first if this is required.
