### ISSUE TITLE
Falling docker build

### ISSUE THREAD

**Issue by rod-stuchi** [svenfuchs/i18n-active_record#117]
Hi, maybe a silly question.

I need to build a docker image, but without need to supply a database connection.

when I exec this step
```console
bundle exec rails webpacker:install
```

I get this error:

![image](https://user-images.githubusercontent.com/19471811/131714590-139b5cee-bc9b-4016-9801-a81e9fc87eef.png)

```
ruby 2.6.6
rails 6.0.3
i18n-active_record latest
```

**Comment by timfjord** [comment]
It looks like you need to update the `i18n_active_record.rb` initializer as it triggers the `table_exists?`call which causes a database connection
You could, for example, add an ENV variable to avoid `table_exists?` check
```console
SKIP_I18N_ACTIVE_RECORD_INIT=1 bundle exec rails webpacker:install
```
and slightly change the initializer
```ruby
return if ENV['SKIP_I18N_ACTIVE_RECORD_INIT'].present?

require 'i18n/backend/active_record'

# ...
```

**Comment by rod-stuchi** [comment]
Hi @timfjord , thank you for the help.
Your solution solved the problem.

I owe you a :beer:
