### ISSUE TITLE
Add additional config options `fallback_to_default_locale` and `raise_exception_on_missing`

### ISSUE THREAD

**Issue by westonganger** [svenfuchs/i18n-active_record#123]
It would be cool to add some additional config options, `fallback_to_default_locale` and `raise_exception_on_missing`

Example:

```
I18n::Backend::ActiveRecord.configure do |config|
  config.fallback_to_default_locale = true
  config.raise_exception_on_missing = true
end

**Comment by timfjord** [comment]
@westonganger have you seen https://github.com/ruby-i18n/i18n/blob/master/lib/i18n/backend/fallbacks.rb?
It is designed to handle fallbacks in the `i18n` gem

As for the `raise_exception_on_missing`, cannot it be achieved with the `I18n.exception_handler`(https://github.com/ruby-i18n/i18n/blob/0888807ab2fe4f4c8a4b780f5654a8175df61feb/test/i18n_test.rb#L143-L150)?
