### ISSUE TITLE
cache_translations = true not respected if translations table is empty

### ISSUE THREAD

**Issue by mauro-oto** [svenfuchs/i18n-active_record#126]
If the `translations` table is empty, every time you call `I18n.t("foo")` it still runs `SELECT "translations".* FROM "translations"` regardless of the `cache_translations = true` setting.

```
[1] pry(main)> Translation.delete_all
  I18n::Backend::ActiveRecord::Translation Destroy (2.3ms)  DELETE FROM "translations"
=> 1
[2] pry(main)> I18n.t("foo")
  I18n::Backend::ActiveRecord::Translation Load (1.0ms)  SELECT "translations".* FROM "translations"
=> "translation missing: en.foo"
[3] pry(main)> I18n.t("foo")
  I18n::Backend::ActiveRecord::Translation Load (0.8ms)  SELECT "translations".* FROM "translations"
=> "translation missing: en.foo"
[4] pry(main)> I18n.t("foo")
  I18n::Backend::ActiveRecord::Translation Load (0.6ms)  SELECT "translations".* FROM "translations"
=> "translation missing: en.foo"
[5] pry(main)> I18n.t("foo")
  I18n::Backend::ActiveRecord::Translation Load (0.9ms)  SELECT "translations".* FROM "translations"
=> "translation missing: en.foo"
```

Having at least one record in the `translations` table avoids this problem. Likely because of the `empty?` check in:
https://github.com/svenfuchs/i18n-active_record/blob/426f757659dfd962f606ad1cf0c1bd6944ca832f/lib/i18n/backend/active_record.rb#L84

Doesn't seem like it was intended behavior, especially since cache should get invalidated after a commit on the table anyway.

**Comment by timfjord** [comment]
Good spot @mauro-oto 
Let me try to fix it and will come bac kto you

**Comment by timfjord** [comment]
It is fixed now https://github.com/svenfuchs/i18n-active_record/releases/tag/v1.0.1
