### ISSUE TITLE
Breaks on latest i18n

### ISSUE THREAD

**Issue by mpantel** [svenfuchs/i18n-active_record#130]
When upgrading to latest i18n (1.9.0) rails fails to start.
Rolling back to 1.8.11 fixes the issue.

Last line of console traceback is:

../local_gems/ruby/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require': cannot load such file -- i18n/core_ext/hash (LoadError)

**Comment by mpantel** [comment]
i18n >= 1.9.1 fixes this, but patch is still relevant

**Comment by timfjord** [comment]
Closing this issue as the bug has been already fixed in `i18n` and `i18n#1.9.0`has been yanked.
