### ISSUE TITLE
Update example article for Rails 5.1

### ISSUE THREAD

**Issue by wrycoder** [svenfuchs/i18n-active_record#138]
When I tried to go through the steps in the example... 

http://collectiveidea.com/blog/archives/2016/05/31/beyond-yml-files-dynamic-translations/ 

...my test kept failing. It appeared as if the TranslationsController was being ignored. The locale was never set, but the application views still loaded. After lots of trial and error, I came across this post:

https://stackoverflow.com/questions/16519828/rails-4-before-filter-vs-before-action

It looked as if the example was using a method that has now been removed from Rails. When I changed before_filter to before_action, everything worked. Could the example article be updated?

**Comment by timfjord** [comment]
I am afraid I don't have access to the article so I won't be able to correct it.  
At the same time, I would like to keep the article in the README.

What I can do is note that the article is not suitable for Rails 5.1+

**Comment by timfjord** [comment]
Here we go https://github.com/svenfuchs/i18n-active_record/commit/1fe4b9150c3eee9a8f9a5e8e2b90580280a7aec1

**Comment by wrycoder** [comment]
Thanks!
