### ISSUE TITLE
Code reloading with Zeitwerk

### ISSUE THREAD

**Issue by 23tux** [svenfuchs/i18n-active_record#143]
My model `Translation` has some custom behaviour, validations... that I added like this:

```
# app/models/translation.rb
Translation = I18n::Backend::ActiveRecord::Translation
class Translation
  VALUES = ["foo", "bar"]
  validates :key, inclusion: { in: VALUES }
end
```

In development when I change a file the code gets reloaded by Zeitwerk. Alas, the constant `I18n::Backend::ActiveRecord::Translation` is not reloaded by Zeitwerk, as it's part of the gem and therefore not in an autoload path.

This results in redefining `validates :key, ...` and having multiple validations for `:key`, and it triggers `warning: already initialized constant VALUES` because the constant still lives on `I18n::Backend::ActiveRecord::Translation`.

I think if I could provide a custom class that inherits from `I18n::Backend::ActiveRecord::Translation` and that lives entirely in an autoload path, this could solve the reloading problem:

```
class Translation < I18n::Backend::ActiveRecord::Translation
  VALUES = ["foo", "bar"]
  validates :key, inclusion: { in: VALUES }
end
```

But as far as I know, there is no way to configure the gem with a custom class, right? Or is there a way to achieve this?

**Comment by timfjord** [comment]
Hi @23tux,

Unfortunately, there is no way to specify a custom class.
But we have recently added a config, so adding support for the custom class shouldn't be complicated.
Please feel free to submit a PR.

In the meantime, you could work out your problem by introducing a wrapper that handles translation updates.

**Comment by 23tux** [comment]
I'm currently managing the reloading of code myself, but IMO it's pretty complicated, especially as I have a constant in the namespace of `Translation`:

```
# tell zeitwerk to ignore those files, as we are doing the require ourselves
Rails.autoloaders.main.ignore(
  Rails.root.join("app/models/translation.rb"),
  Rails.root.join("app/models/translation/key_filter.rb")
)

# to_prepare can be called multiple times during a code reload, so we might do the same stuff multiple times, which is not ideal
Rails.configuration.to_prepare do
  if I18n::Backend::ActiveRecord::Translation.const_defined?(:KeyFilter)
    I18n::Backend::ActiveRecord::Translation.send(:remove_const, :KeyFilter)
  end
  I18n::Backend::ActiveRecord.send(:remove_const, :Translation)
  Object.send(:remove_const, :Translation) if Object.const_defined?(:Translation)

  # a simple require(...) would not reload the files, so we have to force it using load
  load("#{Gem.loaded_specs.fetch("i18n-active_record").full_gem_path}/lib/i18n/backend/active_record/translation.rb")
  load(Rails.root.join("app/models/translation.rb"))
  load(Rails.root.join("app/models/translation/key_filter.rb"))
end
```

@timfjord I'll be happy to try for a PR if I find some free time. Could you give me some guidance where to start?

**Comment by timfjord** [comment]
Sure, first of all, I would add a config item here https://github.com/svenfuchs/i18n-active_record/blob/master/lib/i18n/backend/active_record/configuration.rb (making sure `Translation` is the default value )
Then I would go to https://github.com/svenfuchs/i18n-active_record/blob/master/lib/i18n/backend/active_record.rb and make sure that instead of the `Translation` model something like `self.class.config.translation_model`(or whatever the name would be) is used

**Comment by timfjord** [comment]
Implemented in https://github.com/svenfuchs/i18n-active_record/pull/144
