### ISSUE TITLE
Gem release for Rails 3.1 compatibility

### ISSUE THREAD

**Issue by matthewrudy** [svenfuchs/i18n-active_record#21]
It seems the problem has been fixed;
* b3bb11e152c5bb54a4f836ba598b1562f38b35ba
* 68de9c3e6b16520c670f46c58b164a2ed1e0900b 

But is it possible to get a 0.0.3 gem release with these fixes?
Would be much appreciated.

Thanks for your help.

**Comment by timsly** [comment]
Probably it's not relevant anymore, but in next days i will release gem. It should also include rails 3 support
