### ISSUE TITLE
Added to attributes on the translation

### ISSUE THREAD

**Issue by wdiechmann** [svenfuchs/i18n-active_record#34]
Hi Sven Fuchs,

thank you very much for sharing!

I've forked the I18n-active_record gem and added ox_id and state to the translation in order to

- publish only translation ready for 'production'
- translate only keys belongs_to some superstructure (oxen in my scenario)

The ox_id will allow me to hold a number of translations specific to individual use cases, in _one table_ like 

- use case #1 will translate citizen into 'bürger¨
- use case #2 will translate citizen into "anwender"

all within the same Rails app (effectively providing me with means to run multiple customized use cases off one Rails app)

I'm not good at writing tests - and when I tried to ```rake test```after cloning - it failed utterly on me, which probably is my fault more than I18n-active_record - but anyway, just to emphasize that I have not been able to add any tests, should you want me to 'pull a request' :)

cheers,
Walther

**Comment by timsly** [comment]
I fixed test suit in the latest release. So feel free to do PR, but please make sure tests are passing.
Do not forget to run `bundle install`  before.
