### ISSUE TITLE
serialize problems

### ISSUE THREAD

**Issue by slbug** [svenfuchs/i18n-active_record#4]
i'm using i18n-active_record backend with rails master. in i18n initializer i have following code:
<pre>
I18n::Backend::ActiveRecord.send(:include, I18n::Backend::Flatten)
I18n::Backend::ActiveRecord.send(:include, I18n::Backend::Memoize)
I18n::Backend::Simple.send(:include, I18n::Backend::Memoize)
I18n::Backend::Simple.send(:include, I18n::Backend::Pluralization)
I18n::Backend::Chain.send(:include, I18n::Backend::ActiveRecord::Missing)

I18n.backend = I18n::Backend::Chain.new(I18n::Backend::Simple.new, I18n::Backend::ActiveRecord.new)
</pre>

And because of 'serialize :value' in lib/i18n/backend/active_record/translation.rb AR serializes every field named value in any model, but everything ok using rails 3.0.3. 
Seems like they changed something in include proccess and it includes 'serialize :value' and 'serialize :interpolations' to every model.
Can you please check it?

**Comment by timsly** [comment]
Issue is quite old, so i am not sure if it is still relevant. So closing this for now.
