### ISSUE TITLE
Present unique available locales

### ISSUE THREAD

**Issue by gabrielengel** [svenfuchs/i18n-active_record#51]
1.9.3p448 :001 > I18n.available_locales
  I18n::Backend::ActiveRecord::Translation Load (117.4ms)  SELECT DISTINCT "translations".* FROM "translations"
 => [:en] 

1.9.3p448 :002 > I18n::Backend::ActiveRecord::Translation.available_locales
  I18n::Backend::ActiveRecord::Translation Load (10.6ms)  SELECT DISTINCT "translations".* FROM "translations"
 => [:en, :en, :en, :en, :en, :en, :en, :en, :en, :en, :en, :en, :en, :en, :en, :en, :en, :en, :en, :en,..]

**Comment by timsly** [comment]
Just added test case to reproduce this issue. (see de26f7b34958860c4dba48bdefb9fa64a831d3a6)
Tests were green.
Closing it for now
