### ISSUE TITLE
active_record/missing no longer functions

### ISSUE THREAD

**Issue by pctj101** [svenfuchs/i18n-active_record#56]
https://github.com/svenfuchs/i18n-active_record/blob/master/lib/i18n/backend/active_record/missing.rb#L57

It looks like I18n no longer raises the Exception MissingTranslationData, and instead throws an exception which is caught by I18n::ExceptionHandler which does not rethrow MissingTranslation and instead returns "translation missing: key_name".  
https://github.com/svenfuchs/i18n/blob/master/lib/i18n/exceptions.rb#L13

Thus there is no error, and nothing to rescue, and thus this module does nothing.

I can hack the functions from Missing into a new ExceptionHandler and do what I want.  But is there a better way?

**Comment by timsly** [comment]
I am not sure if this is still relevant, but this issue will be fixed in #65
