### ISSUE TITLE
Rails4 compatible release

### ISSUE THREAD

**Issue by demental** [svenfuchs/i18n-active_record#58]
Hi Sven !
Master branch is used by OneSky for translations database backend, so I added this repo as a dependency for my project. Just let me know when/wether you plan to tag the current state, which seems rails 4 compatible.

**Comment by paulgoetze** [comment]
This very handy gem works for me too on Rails 4.2. Nice work @svenfuchs! I was just wondering whether there is a reason for not publishing the latest changes as a new gem release. I would love to see that! At least for production apps  it seems not to be the best idea to depend on a github branch that is likely to change.

**Comment by icatcher-at** [comment]
:+1:

**Comment by timsly** [comment]
I will release gem in next few days. Keep an eye on #65

**Comment by paulgoetze** [comment]
:+1:  Awesome @timsly, thank you!
