### ISSUE TITLE
Rails app crashes when a null locale is present

### ISSUE THREAD

**Issue by sajoku** [svenfuchs/i18n-active_record#59]
Today I was investigating a startup failure in a Rails app with the following error:

```
/Users/sajoku/.rvm/gems/ruby-2.2.0/bundler/gems/i18n-active_record-2d9a22b6a4e5/lib/i18n/backend/active_record/translation.rb:76:in `block in available_locales': undefined method `to_sym' for nil:NilClass (NoMethodError)
        from /Users/sajoku/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/delegation.rb:46:in `map'
```

After some investigation the error led me (and my pair buddy) to the translations table in the database and check all the translations. The last two entries had NULL as :locale. Removing this fixed the startup issue.

I'm not sure if my "fix" is desirable but wanna check this out and let me know what you think?
https://github.com/sajoku/i18n-active_record/commit/2f563cda95587f594de8ea3cabe27c47e8c30ecd
The reason I'm not sure is because this seems to be something the user could simply fix by making sure locale has a default value or can't be NULL in the database. What are your thought on this?

Or maybe let the user know in te README (or wiki perhaps?)?
https://github.com/sajoku/i18n-active_record/commit/b284fee03a7cb858af77aaa95909a79a61fd6dad

**Comment by sajoku** [comment]
@CDingerdis This is the issue we ran in to. Wanna check out the proposed solution?

**Comment by rvfx** [comment]
Thank you, this information helped me alot!

**Comment by sajoku** [comment]
@rvfx Awesome 😄

I haven't tested this with anything other  than MySQL though, so be careful just implementing this with anything other than that.

**Comment by timsly** [comment]
Hey @sajoku 
Why don't you submit a PR with your fix.
I think `IS NOT NULL` is ok for all major sql adapters that we support

**Comment by sajoku** [comment]
A bit late but I'll close this issue as I believe this is a non-issue for other people.
