### ISSUE TITLE
Refactoring: renaming of column Translation#key because it's a reserved word for MySQL

### ISSUE THREAD

**Issue by volontarian** [svenfuchs/i18n-active_record#60]
The key column of Translation model should be renamend because key is a reserved word for MySQL or how do you get queries with key column as criteria working? I'm using MySQL 5.6.14.
See also http://dev.mysql.com/doc/refman/5.7/en/reserved-words.html

E.g. "SELECT DISTINCT(key) FROM translations;" throws:

    You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key) FROM translations' at line 1

If the column can be renamed then I would volunteer for it to do the refactoring and make a pull request. Therefor I need to know the new name for the column? I cannot find a good name.

**Comment by k3rni** [comment]
http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/Quoting.html#method-i-quote_column_name

That is, if you have to build queries like `where("key LIKE ?", stuff)`, you should replace them with something like:

```ruby
  col = Translation.connection.quote_column_name "key"
  Translation.where("#{col} LIKE ?", stuff)
```

and the database adapter will mangle the column accordingly. MySQL is picky about "key" in particular, but the driver wraps whatever you pass in backticks; while e.g. the Postgresql driver wraps in doublequotes.

**Comment by rsmithlal** [comment]
```
SELECT DISTINCT(`key`) FROM translations;
```
should work fine. Just use backticks to escape the field like you would do if it had invalid characters, such as 

```
select * from `database-with-dashes` where `database-with-dashes`.`attribute-with-dashes` is not null;
```

**Comment by timsly** [comment]
@volontarian please follow @rsmithlal's suggestion
