### ISSUE TITLE
Time for a push to rubygems?

### ISSUE THREAD

**Issue by dmiller-iseatz** [svenfuchs/i18n-active_record#63]
The last version that was pushed to rubygems was 0.0.2 in 2010: `0.0.2 - December 26, 2010`

Perhaps it is time to push a new version? It seems like there have been several changes since then.

**Comment by dmiller-iseatz** [comment]
I would like to use i18n-active_record in a personal gem that will be used in Rails 4 projects. However, I cannot specify i18n-active_record in the gemspec as a github based gem.

**Comment by 5minpause** [comment]
Yes, there is definitely need for a new version on Rubygems.

**Comment by mochtu** [comment]
+1

**Comment by timsly** [comment]
I will try to push the latest stable state of the gem this week.

**Comment by timsly** [comment]
Once #65 will be merged - i will release gem.
