### ISSUE TITLE
How to use table of different name?

### ISSUE THREAD

**Issue by sixtyfive** [svenfuchs/i18n-active_record#66]
Hi, I need to move from YAML files to a database table for storing i18n data, but already have a model "Translation" in my app which is used otherwise. Is there any way to get i18n-active_record to use a different model and database table?

**Comment by timsly** [comment]
@sixtyfive there is no configuration option to change this, but you can do it by changing `table_name` directly. Try something like: `I18n::Backend::ActiveRecord::Translation.table_name = 'my_table_for_translations'` in the initializer.

Also, maybe make sense to add namespace for the table later. So by default it will be smth like `i18n_translations`. This can be done in next releases.

I am closing this issue for now, feel free to reopen it if my suggestion won't work for you.

**Comment by sixtyfive** [comment]
Thank you for the speedy response @timsly! For my purposes your suggestion will be plenty good, but yeah, the idea about using a namespace sounds mighty fine as well!
