### ISSUE TITLE
Translations don't get updated quickly

### ISSUE THREAD

**Issue by zenati** [svenfuchs/i18n-active_record#67]
Hello,

I'm using the gem and everything works good except that when I translate/update-translation something, it takes seconds and sometimes I need to reboot rails for the change to take effect. Is there a cache or something that makes that happen? May be related to unicorn?

Thanks

**Comment by zenati** [comment]
:up:

**Comment by timsly** [comment]
@zenati look to issue #13. I think `I18n.backend.reload!` should help.
So closing this one for now

**Comment by Sylvain-Kraisin** [comment]
@zenati i have the same problem and I18n.backend.reload! not working for me. Did you fix your issue ?
