### ISSUE TITLE
What happened to the rails-4-release branch?

### ISSUE THREAD

**Issue by rsmithlal** [svenfuchs/i18n-active_record#69]
I was using it for my rails 4 app, did it get merged into master and deleted? You should create a rails 4 release tag so we can have a reliable rails 4 version not subject to the working changes in master... The rubygems version is too old to use reliably. 0.1.0 was released in 2013!

**Comment by timsly** [comment]
Rails 4 compatible version(0.1) was released last week.

We don't need a tag, because this version is compatible with rails 3, 4 and
5
25 бер. 2016 р. 02:29 "Robert Smith" <notifications@github.com> пише:

**Comment by rsmithlal** [comment]
Thanks for the info! You should mention this change in the readme in case more people have specified the rails-4-release branch in their gemfiles. Keep up the great work on this project! It's an invaluable gem for rails apps!
