### ISSUE TITLE
User defined methods for I18n::Backend::ActiveRecord::Translation

### ISSUE THREAD

**Issue by augustosamame** [svenfuchs/i18n-active_record#74]
Hi. I am trying to select the locale using a dropbox in a view.

This works fine:

```
<%= collection_select :selected_locale, :locale,
        Translation.select(:locale).distinct, :locale, :locale,
        {:selected => 'en'} %>
```

However, when trying to use a user-defined method for a friendlier locale name:

```
<%= collection_select :selected_locale, :locale,
        Translation.select(:locale).distinct, :locale, :friendly_locale_name,
        {:selected => 'English'} %>
```

I get the following error:

`ActionView::Template::Error (undefined method 'friendly_locale_name' for #<I18n::Backend::ActiveRecord::Translation id: nil, locale: "es">):`

I am defining friendly_locale_name in my Translation model which I guess is inheriting from `I18n::Backend::ActiveRecord::Translation`, so I don't understand why this fails.

```
class Translation < ActiveRecord::Base

  attr_accesor :friendly_locale_name

  def friendly_locale_name
    case self.locale
      when 'en'
          return 'English'
      when 'es'
        return 'Español'
      else
        return self.locale
    end
  end

end


```
Any help would be appreciated

**Comment by timsly** [comment]
Hi @augustosamame 
In class that you pasted `Translation` inherits from `ActiveRecord::Base`.
And it's working only because by default AR map this model to `translations` table.
You can try
```ruby
I18n::Backend::ActiveRecord::Translation.class_eval do
  def friendly_locale_name
    # your methods goes here
  end
end
```
and then in view 
```erb
<%= collection_select :selected_locale, :locale,
        I18n::Backend::ActiveRecord::Translation.select(:locale).distinct, :locale, :friendly_locale_name,
        {:selected => 'English'} %>
```

**Comment by augustosamame** [comment]
That worked flawlessly. Thank you!
