### ISSUE TITLE
Conflict with Rails 5 initializers order

### ISSUE THREAD

**Issue by mauro-oto** [svenfuchs/i18n-active_record#78]
Hi,

I have a newly created Rails 5.0.1 app which I added this gem to, and everything worked as expected.
 
However, a test began failing. The test was a unit test that checked whether a model's `belongs_to` association was working properly, and we are using the new Rails 5 ["implicit" `belongs_to` validation](http://blog.bigbinary.com/2016/02/15/rails-5-makes-belong-to-association-required-by-default.html). 

Turns out that Rails 5.0.1 creates an initializer named `new_framework_defaults.rb`, and the README for this gem recommends creating an initializer named `locale.rb`. The thing is, `locale.rb` runs first, it does the set up, and only then `new_framework_defaults.rb` sets `config.active_record.belongs_to_required_by_default = true`.
 
I worked around it by creating an earlier initializer, `active_record_belongs_to_required_by_default.rb`, but this should probably be fixed in the gem itself. 

There's a bunch of gems with this issue, and some of them have already merged PR's, see: https://github.com/rails/rails/issues/23589. 

Thanks for creating this gem! :+1:

**Comment by timsly** [comment]
Hi @mauro-oto 
I am not sure this can be somehow fixed in this gem.
There is no generators here, so you can control naming on your side.
You can rename i18n-active_record initializer to `translation.rb`, this way rails will evaluate it after `new_framework_defaults.rb`

**Comment by mauro-oto** [comment]
@timsly cool, I did work around it that way in my app. But still, I think we could change the recommended initializer name in this gem's `README` from `locale.rb` to something like `translation.rb`, as you mentioned. What do you think?

**Comment by timsly** [comment]
@mauro-oto I think we can leave rails 5 notes in the README where we can mention that. So feel free to add PR with that.
