### ISSUE TITLE
Fetch translations subtree

### ISSUE THREAD

**Issue by fatbeard2** [svenfuchs/i18n-active_record#79]
Hi. I've stumbled upon such an issue. Lets say I have the following translation keys:
```
notifications.types.achievment_gained.message
notifications.types.content_created.message
```
If I want to fetch a subtree of my translations stored in database using `notifications.types` key it will return me a hash like this:
```ruby
{:"achievement_gained.message"=>"achievement was gained",
 :"content_created.message"=>"content was created"}
```
But in order to correctly merge it with translations from other backends( I am using `I18n::Backend::Chain`) it should return hash like this

```ruby
{:achievement_gained=>{:message=>"achievement was gained"},
 :content_created=>{:message=>"content was created"}}
```
Will you accept a PR with a fix for this?

**Comment by timsly** [comment]
Hi @fatbeard2 
Feel free to open the PR. This way it will much easier to understand what you want to fix.
You can just share an idea and add specs later on

**Comment by fatbeard2** [comment]
I created a request https://github.com/svenfuchs/i18n-active_record/pull/80

Not sure why the build is failing, but specs are passing locally for mysql
