### ISSUE TITLE
Bug in Activerecord/YAML chained backend?

### ISSUE THREAD

**Issue by xinspire** [svenfuchs/i18n-active_record#84]
I have locales :en, :es, and :zh-TW.  For each locale, I have a default YAML translation file.  When I supply custom translations for all three locales, it works correctly.  When I override ONLY the :en translation using ActiveRecord, the translations for the same key in :es and :zh-TW change to the custom :en translation instead of falling back to the YAML files (es.yml or zh-TW.yml).

**Comment by timsly** [comment]
Hm, interesting. 
I am just not sure if this issue is related to `ActiveRecord` adapter or to `I18n::Backend::Chain` itself.
But I will take a look, but a bit later.
A PR is also welcome :-)

**Comment by xinspire** [comment]
Turns out it might not be a bug.  The solution is to add the `{ fallback: false }` as an option to translate.

**Comment by timsly** [comment]
Closing it, since the solution has been found
