### ISSUE TITLE
New translations appears in front only after restarting the server (Rails 5.1.3 / Gem Rails_Admin)

### ISSUE THREAD

**Issue by Sylvain-Kraisin** [svenfuchs/i18n-active_record#85]
In my app, the BO is handle by Rails_Admin. 

My translation model is displayed correctly and all the actions are working (create, edit, delete). I check in DB, and everything is updated. 

The problem is, when i go see my page from the browser, even after a refresh, the old translation is still there. If i manually restart the server, the new one will be displayed.

I tried `I18n.backend.reload!`and `Rails.cache.clear`in my console but it doesn't fix anything.

**Comment by fmh** [comment]
same issue !

**Comment by fmh** [comment]
After some test, it seems that it is a problem related to the logic of rails_admin and not an i18n-active_record issue, It will be necessary to reload the rails_admin files (config and models if rails_admin config in models) after each addition or update of translation
Add this code in your translation model and voila, I hope this will help you : 
```ruby
class Translation  < ActiveRecord::Base
  after_save :reload_models
  after_commit :reload_models

  def reload_models
    RailsAdmin.config.models.collect {|m| m.abstract_model.model_name}.each do |m|
      RailsAdmin.config.reset_model(m)
    end
    RailsAdmin::Config::Actions.reset
    load("#{Rails.root}/config/initializers/rails_admin.rb")
    (Dir[Rails.root.join('app', 'models/*.rb')]).each do |f|
      load f
    end
  end
end
````

**Comment by timsly** [comment]
Good catch @fmh 
I am closing this one in the meantime. Feel free to reopen it if issue still exists
