### ISSUE TITLE
Error /app/app/models/translation.rb:1:in `<top (required)>': superclass mismatch for class Translation (TypeError)

### ISSUE THREAD

**Issue by eduardorph** [svenfuchs/i18n-active_record#92]
I followed this [article](http://collectiveidea.com/blog/archives/2016/05/31/beyond-yml-files-dynamic-translations/) to implement translations through a admin page

This works great in my localhost, but when i push to heroku this message appears:

"/app/app/models/translation.rb:1:in `': superclass mismatch for class Translation (TypeError)"

My MODEL TRanslation:

class Translation < ApplicationRecord
end

Can anyone help me, i don't have any idea to solve this

**Comment by timsly** [comment]
Why do you need your own `Translation` model?
There is `Translation` model defined in this gem - https://github.com/svenfuchs/i18n-active_record/blob/master/lib/i18n/backend/active_record/translation.rb
So you can use `I18n::Backend::ActiveRecord::Translation` to manage translations

**Comment by Mehonoshin** [comment]
@eduardorph you should either to remove `Translation = I18n::Backend::ActiveRecord::Translation` from initializers, or get rid of `Translation` model.

**Comment by timsly** [comment]
It looks like the issue has been resolved
