### ISSUE TITLE
Feature request: Generator for migration and initializer

### ISSUE THREAD

**Issue by bekicot** [svenfuchs/i18n-active_record#93]
I think a generator for migration and initializer will be very helpful to get the gem work very quick.

**Comment by timsly** [comment]
I like the idea, I will try to implement once I have some free ttime

**Comment by timsly** [comment]
Implemented in https://github.com/svenfuchs/i18n-active_record/pull/94

**Comment by timsly** [comment]
Released as 0.3.0
