### ISSUE TITLE
i18n search yaml file first, then if not found refer to database

### ISSUE THREAD

**Issue by Manidavid** [svenfuchs/i18n-active_record#96]
Using this gem i noticed that i18n search makes the app look in the database for a translation key first, then fall back to config/locales/*.yml files.

I have most of the translation values defined in yml file and few custom values are stored in database translation table, i have query result of 1000+ records contains multiple column values of various joined tables. so when using this gem to translate all the values, every translation key for current locale searches the database first and if not found refers to yaml files, which generates multiple DB queries which slow down the application performance.

The suggestion, reverse the current gem i18n search approach to look in the yaml file for a translation key first, then search in the database based on the lookup configuration option. 

If this approach possible then multiple db queries can be avoided when the yaml file has major translations over database.

If this feature already present in the gem for any such configuration changes for the lookup; please let me know how to use it.
Thanks!

**Comment by timsly** [comment]
@Manidavid Could you please share your `I18n::Backend::Chain` setup?
It seems that the `ActiveRecord` backend goes first in the chain that's why it looks in the DB first

**Comment by Manidavid** [comment]
Please find the the below `I18n::Backend::Chain` setup
```
require 'i18n/backend/active_record'
I18n.backend = I18n::Backend::Chain.new(I18n::Backend::ActiveRecord.new, I18n.backend)
```
from config/initializers/locale.rb

**Comment by timsly** [comment]
The `ActiveRecord` backend goes first in the `Chain`, so it will be the first lookup storage.

Check the setup from the `README`
```ruby
require 'i18n/backend/active_record'

Translation  = I18n::Backend::ActiveRecord::Translation

if Translation.table_exists?
  I18n.backend = I18n::Backend::ActiveRecord.new

  I18n::Backend::ActiveRecord.send(:include, I18n::Backend::Memoize)
  I18n::Backend::Simple.send(:include, I18n::Backend::Memoize)
  I18n::Backend::Simple.send(:include, I18n::Backend::Pluralization)

  I18n.backend = I18n::Backend::Chain.new(I18n::Backend::Simple.new, I18n.backend)
end
```
